pipeline {
  agent any

  tools {
    maven 'maven-3'
  }

  stages {
    stage('Smoke') {
      steps {
        sh 'mvn test -Psmoke'
      }
    }

    stage('Sanity') {
      steps {
        sh 'mvn test -Psanity'
      }
    }

    stage('Regression') {
      steps {
        sh 'mvn test -Pregression'
      }
    }
  }
}
